### ISSUE TITLE
ocamlbuild 4.03 has more restrictive hygiene rules?

### ISSUE THREAD

**Issue by fpottier** [ocaml/ocamlbuild#61] opened 2016-03-03 15:11 UTC
Hello,
Menhir 20151112 builds with ocamlbuild 4.02.3, but does not build with ocamlbuild 4.03+beta1.
The problem seems to be caused by more restrictive hygiene rules.

I call ocamlbuild twice with the same -build-dir (because I wish to build first a library and then an executable file, and they share some modules). This used to be OK and is now rejected. The second invocation finds a nonempty build directory and complains.

I have worked around the problem by adding -no-hygiene.

Is the more restrictive hygiene discipline intentional?

**Comment by gasche** [comment] 2016-03-03 15:38
There is a known and relatively-intentional change in behavior when you build twice with *different* build-dirs. It comes from #50 , itself coming from a feature-request by Daniel @dbuenzli Bünzli to be able to build files whose name starts with `_`. OCamlbuild would probably ignore all such files; if you happened to name an old build dir with a starting `_`, it would be ignored by following runs with a different build dir. Now that this restriction has been removed, ocamlbuild cannot guess that the old directory is not a source dir (it doesn't remember it used to be a build dir), so it complains. I thought of this issue when making the change, see the discussion [there](https://github.com/gasche/ocamlbuild/commit/01df1248caf8e6f055a67c74cc1bc73f931ee1dc#commitcomment-15982151) and [this change](https://github.com/ocaml/ocamlbuild/pull/50/files#diff-329b2e708262534068b960569612dcebR27) in the ocamlbuild own bootstrap tests, which may be a good workaround for you as well.

I am not aware of any change of behavior if you build several times consecutively with the same build-dir, and that seems strange to me. I will try to reproduce and fix it.

Thinking of this issue again, it now occurs to me that ocamlbuild could use a simple heuristic to recognize things that look like build dirs (typically the presence of a `_log` file). We could traverse them by default and print a warning instead ("This looks like a build dir, but it is not the current build dir, please either mark it `traverse` or `-traverse` explicitly."). That said, it is hard to insert these special cases without making the tool more fragile -- as we learned from Daniel's attempt to compile C files with names starting with `_`.

**Comment by gasche** [comment] 2016-03-03 17:19
So I tried to reproduce (why doesn't the top-level menhir Makefile have a `clean` target? This made my life (slightly) harder.). I think that this is an instance of the change of behavior I described above: you do not always build with the same build dir, but you use several build dirs in succession. Adding

```
# temporary build directories
<_build>: -traverse
<_stage*>: -traverse
```

to `src/_tags` seems to fix the problem.

From your report it sounds like the overlap in build directories might be intentional: are you expecting ocamlbuild to find build objects in one of the previous build-dirs are reuse them instead of rebuilding them afresh?

**Comment by fpottier** [comment] 2016-03-03 17:35
I was wrong, I do not use the same build-dir twice.

My usage pattern is as follows:
  ocamlbuild -build-dir _build <library>
  ocamlbuild -build-dir _stage1 <executable>
  ocamlbuild -build-dir _stage2 <executable>

The third call is independent of the previous two, except it needs to execute _stage1/executable.

With ocamlbuild 4.03, the second call fails because _build is around and ocamlbuild doesn't like it.
With ocamlbuild 4.02, this used to work.

Your proposed fix in src/_tags works. Which is preferrable, use your fix or just use -no-hygiene?

Thanks,
F.

**Comment by gasche** [comment] 2016-03-03 19:21
The _tags fix is strongly preferable, as it allows ocamlbuild to still
check hygiene in the (rest of the) build tree. (People sometimes assume
that hygiene is there just to annoy them, and although there is a bit of
that, it's also true that the semantics of build systems are not
well-defined if the tools cannot distinguish source artifacts from build
artifacts.). It's a local fix, rather than a global one.

**Comment by whitequark** [comment] 2017-03-01 21:37
Closing as there is a working solution.

**Closed by whitequark** 2017-03-01 21:37 UTC
Labels: question
