### ISSUE TITLE
ppopt and ppxopt options

### ISSUE THREAD

**Issue by Drup** [ocaml/ocamlbuild#45] opened 2016-01-18 15:27 UTC
It doesn't seem possible to add these ocamlfind options in the `_tag` file

**Comment by gasche** [comment] 2016-01-18 15:49
Indeed; a pull request would be warmly welcome.

**Comment by whitequark** [comment] 2017-03-01 21:25
Duplicate of #190, which has more context.

**Closed by whitequark** 2017-03-01 21:25 UTC
Labels: duplicate

**Comment by argent-smith** [comment] 2017-12-26 20:12
I've just encountered this issue: lwt docs say I can use ppxopt tag to specify -ppxopt lwt.ppx,-no-debug but I get "Warning: tag "ppxopt" does not expect a parameter, but is used with parameter "lwt.ppx,-no-debug" when compiling.

**Comment by gasche** [comment] 2018-01-02 10:13
Thanks for the (reiterated) request, I proposed an implementation in https://github.com/ocaml/ocamlbuild/pull/265.
